"""empty message

Revision ID: 104cd35532ef
Revises: 
Create Date: 2020-02-10 22:52:58.715403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '104cd35532ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('total_cats', sa.Integer(), nullable=False),
    sa.Column('cat_knowledge_level', sa.Integer(), nullable=False),
    sa.Column('puppy_subscribed', sa.Boolean(), nullable=False),
    sa.Column('br_state', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscribers')
    # ### end Alembic commands ###
