"""empty message

Revision ID: 7322e6d89508
Revises: 104cd35532ef
Create Date: 2020-02-10 23:13:41.473543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7322e6d89508'
down_revision = '104cd35532ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers', sa.Column('puppy_castrated', sa.Boolean(), nullable=False))
    op.drop_column('subscribers', 'puppy_subscribed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers', sa.Column('puppy_subscribed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('subscribers', 'puppy_castrated')
    # ### end Alembic commands ###
