"""empty message

Revision ID: 858ebeb92042
Revises: 7322e6d89508
Create Date: 2020-02-10 23:17:18.746644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '858ebeb92042'
down_revision = '7322e6d89508'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers', sa.Column('color', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscribers', 'color')
    # ### end Alembic commands ###
